#!/bin/bash
# run_full_audit.sh — chạy cái này là xong

set -e

BLUEPRINT="audit/CLONE_BLUEPRINT.md"
mkdir -p audit

echo "════════════════════════════════════"
echo " Spendo Clone Blueprint Audit"
echo "════════════════════════════════════"

# ── Phase 0: Pre-bundle ───────────────
echo ""
echo "[Phase 0] Pre-bundling codebase..."
bash scripts/pre_bundle.sh

BUNDLE_SIZE=$(wc -l < "audit/context_bundle.md")
echo "Bundle: $BUNDLE_SIZE lines"

# ── Phase 1: Index pass ───────────────
echo ""
echo "[Phase 1] Index pass (stack + schema + routes)..."

cat > "$BLUEPRINT" << 'EOF'
# Spendo — Clone Blueprint
> Auto-generated by Clone Audit Agent

EOF

codex \
  --sandbox workspace-write \
  --ask-for-approval never \
  exec \
  -C . \
"
Read the file: audit/context_bundle.md

From this file only, document the following sections and write to $BLUEPRINT (OVERWRITE with full content so far):

# Spendo Clone Blueprint

## 1. Tech Stack & Dependencies
Table: | Package | Version | Role | Setup Complexity |
Include ALL packages from pubspec.yaml.
Flag any that need native setup, OAuth config, or API keys.

## 2. Project Structure
Explain the folder architecture. 
Show which folder = which layer (presentation / domain / data / core).

## 3. Data Models
For each model class found: fields, types, serialization method, which DB table it maps to.

## 4. PowerSync Schema
List every table, columns, types, sync rules.

## 5. Supabase Integration
Tables queried, auth methods, RLS assumptions.

## 6. Navigation Map (Go Router)
Every route: path, screen, params, guard.
Include ASCII tree of navigation.

## 7. Theme & Design System
Primary color hex, typography scale, key component overrides.

## 8. CI/CD Summary
Build steps, signing, deploy targets.

Write ONLY what you find in the file. Say 'Not found' if missing.
"

echo "✅ Phase 1 done"

# ── Phase 2: Feature-by-feature ───────
echo ""
echo "[Phase 2] Feature-by-feature audit..."
bash scripts/run_feature_audit.sh

# ── Phase 3: Synthesis ────────────────
echo ""
echo "[Phase 3] Final synthesis..."

codex \
  --sandbox workspace-write \
  --ask-for-approval never \
  exec \
  -C . \
"
Read the current content of: $BLUEPRINT

Based on everything documented above, APPEND these final sections:

## TL;DR Cheatsheet

### Stack
| Layer | Technology | Notes |
|-------|-----------|-------|

### Feature Complexity
| Feature | Complexity | Key Dependencies | Est. Days |
|---------|-----------|-----------------|-----------|

### External Services
| Service | Purpose | Auth Method | Risk if Unavailable |
|---------|---------|------------|---------------------|

## Clone Recommendations

### Phase 1 — MVP (Must have)
List features essential for a working app.

### Phase 2 — Growth
List features to add after MVP.

### Top 10 Implementation Gotchas
Numbered list of the trickiest parts found in codebase.

### Suggested Rebuild Stack
If rebuilding today, what would you keep vs replace, and why.

Append to: $BLUEPRINT
"

echo ""
echo "════════════════════════════════════"
echo "✅ DONE → audit/CLONE_BLUEPRINT.md"
wc -l "$BLUEPRINT"
echo "════════════════════════════════════"